FROM couchbase/sync-gateway:community AS stage_base
# COPY sync-gateway.json /etc/sync_gateway/config.json
# COPY bootstrap.json /home/sync_gateway/sync_gateway.json
COPY init-syncgateway.sh /opt/couchbase-sync-gateway/init/init-syncgateway.sh
